name: rocketchat
version: 0.1.5
appVersion: 0.56
description: Prepare to take off with the ultimate chat platform, experience the next
  level of team communications
keywords:
- chat
- communication
- http
- web
- application
- nodejs
- javascript
- meteor
home: https://rocket.chat/
icon: https://pbs.twimg.com/profile_images/1016397063649660929/14EIApTi_400x400.jpg
sources:
- https://github.com/RocketChat/Docker.Official.Image/
engine: gotpl
